"""Initial migration

Revision ID: 0bd0432e9e95
Revises: 
Create Date: 2025-06-23 01:10:16.223524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd0432e9e95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('test_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_info',
    sa.Column('test_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('test_status', sa.VARCHAR(), nullable=False),
    sa.Column('hallucination_score', sa.FLOAT(), nullable=True),
    sa.Column('helpfullness_score', sa.FLOAT(), nullable=True),
    sa.Column('last_test_conducted', sa.DATETIME(), nullable=True),
    sa.Column('question', sa.VARCHAR(), nullable=False),
    sa.Column('student_answer', sa.VARCHAR(), nullable=False),
    sa.Column('difficulty_level', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('test_id', 'user_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('project_name', sa.VARCHAR(), nullable=True),
    sa.Column('content_type', sa.VARCHAR(), nullable=True),
    sa.Column('target_url', sa.VARCHAR(), nullable=True),
    sa.Column('payload_method', sa.VARCHAR(), nullable=True),
    sa.Column('end_point', sa.VARCHAR(), nullable=True),
    sa.Column('header_keys', sa.VARCHAR(), nullable=True),
    sa.Column('header_values', sa.VARCHAR(), nullable=True),
    sa.Column('payload_body', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('test_interval_in_hrs', sa.FLOAT(), nullable=True),
    sa.Column('benchmark_knowledge_id', sa.VARCHAR(), nullable=True),
    sa.Column('registered_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('isVerified', sa.BOOLEAN(), nullable=True),
    sa.Column('verification_token', sa.VARCHAR(), nullable=True),
    sa.Column('registered_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    # ### end Alembic commands ###
